// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-order/internal/sdk/models/shared"
	"net/http"
)

type PatchOrderRequest struct {
	// Order to patch
	OrderPatch shared.OrderPatch `request:"mediaType=application/json"`
	// The order id
	OrderID string `pathParam:"style=simple,explode=false,name=orderId"`
}

func (o *PatchOrderRequest) GetOrderPatch() shared.OrderPatch {
	if o == nil {
		return shared.OrderPatch{}
	}
	return o.OrderPatch
}

func (o *PatchOrderRequest) GetOrderID() string {
	if o == nil {
		return ""
	}
	return o.OrderID
}

type PatchOrderResponse struct {
	// Any error based on client data errors
	ClientError *shared.ClientError
	// HTTP response content type for this operation
	ContentType string
	// Order entity response
	Order *shared.Order
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Any error based on the server-side
	ServerError *shared.ServerError
}

func (o *PatchOrderResponse) GetClientError() *shared.ClientError {
	if o == nil {
		return nil
	}
	return o.ClientError
}

func (o *PatchOrderResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchOrderResponse) GetOrder() *shared.Order {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *PatchOrderResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchOrderResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PatchOrderResponse) GetServerError() *shared.ServerError {
	if o == nil {
		return nil
	}
	return o.ServerError
}
