// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type OrderCreateTotalsDetail struct {
	AmountTax types.Number          `tfsdk:"amount_tax"`
	Breakdown *OrderCreateBreakdown `tfsdk:"breakdown"`
}
