// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Recurrences struct {
	AmountSubtotal        types.Number `tfsdk:"amount_subtotal"`
	AmountSubtotalDecimal types.String `tfsdk:"amount_subtotal_decimal"`
	AmountTax             types.Number `tfsdk:"amount_tax"`
	AmountTotal           types.Number `tfsdk:"amount_total"`
	AmountTotalDecimal    types.String `tfsdk:"amount_total_decimal"`
	Type                  types.String `tfsdk:"type"`
}
