// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Tax struct {
	ID   types.String `tfsdk:"id"`
	Rate types.String `tfsdk:"rate"`
	Type types.String `tfsdk:"type"`
}
