// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

type OrderCreateBreakdown struct {
	Recurrences []Recurrences `tfsdk:"recurrences"`
	Taxes       []Taxes       `tfsdk:"taxes"`
}
