// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type OrderCreateSource struct {
	Href  types.String `tfsdk:"href"`
	Title types.String `tfsdk:"title"`
}
